### ISSUE TITLE
TUTORIAL can not be closed

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#10] opened 2021-01-04 22:32 UTC
If Tutorial menu has been opened - it can not be closed. Black screen appeared with a string "Loading..." Need to exit to lobby and to enter the game again.

**Comment by tbox1911** [comment] 2021-01-05 08:53
should be fixed in the latest version

**Comment by Varrkan82** [comment] 2021-01-05 14:22
> fixed in a previous release

Not fixed. Still present.

**Comment by tbox1911** [comment] 2021-01-05 15:00
I've just test with the latest pbo (in build) and I can't reproduce the issue
i'll try to find the commit

**Comment by tbox1911** [comment] 2021-01-05 15:13
could be in file:
scripts\client\ui\intro.sqf
scripts\client\ui\tutorial_manager.sqf
scripts\client\spawn\redeploy_manager.sqf

try to update these files
(if the issue persist send me the pbo)

**Comment by Varrkan82** [comment] 2021-01-05 15:50
> could be in file:
> scripts\client\ui\intro.sqf
> scripts\client\ui\tutorial_manager.sqf
> scripts\client\spawn\redeploy_manager.sqf
> 
> try to update these files
> (if the issue persist send me the pbo)

An only difference I've found - it are my translations and I've added a one extra item to tutorial_manager.sqf
![image](https://user-images.githubusercontent.com/7004992/103666793-c0422a00-4f7d-11eb-965b-b82addfe2cba.png)
Here is the link to my latest PBO. Select an "ІНСТРУКЦІЯ" menu item.
https://mega.nz/file/9NU0jLaD#kaldqpYhp0wCFVimmwVqpsW1HN7bH4oVo8HX3123aNY

**Comment by tbox1911** [comment] 2021-01-05 15:56
ok, I'll test on my side

**Comment by tbox1911** [comment] 2021-01-05 16:15
strange, tested with your pbo, and it work fine. (in lang fr/en)
It take your idea to put the tip'n trick in tutorial

can you test in english ?
i keep investigate

**Comment by Varrkan82** [comment] 2021-01-05 16:18
> strange, tested with your pbo, and it work fine. (in lang fr/en)
> I take your idea to put the tip'n trick in tutorial
> 
> can you test in english ?
> i keep investigate

I'll try. Thanks.

**Comment by tbox1911** [comment] 2021-01-05 16:27
also try, in local mode (hosted)

because in intro.sqf, I wait for the player read briefing
```
if (isMultiplayer) then {
	waituntil {(time > 2) && (getClientStateNumber >= 10) && (getClientState == "BRIEFING READ")};
```

**Comment by tbox1911** [comment] 2021-01-05 16:32
ok, i'm able to reproduce

**Comment by Varrkan82** [comment] 2021-01-05 16:37
> ok, i'm able to reproduce

Need you some action from my side?

**Closed** 2021-01-05 17:19 UTC

**Comment by Varrkan82** [comment] 2021-01-05 17:48
> I take your idea to put the tip'n trick in tutorial

Please, pay attention, I'm translating to Ukrainian, not to Russian. Arma just not supported Ukrainian and I need to replace Russian in stringtable.xml

**Comment by Varrkan82** [comment] 2021-01-05 18:31
Confirmed fix.
