### ISSUE TITLE
Admin Menu Dropdowns Not Populating

### ISSUE THREAD

**Issue by gkleinfe** [tbox1911/Liberation-RX#24] opened 2021-01-12 00:39 UTC
Using Altis build as of 1/11/21 7:38pm EST to be able to use rename unit feature.  None of the drop down menus in the admin menu are populating.

**Comment by tbox1911** [comment] 2021-01-12 08:43
seem to be ok with version 2/11 @ 19:01
can you retry please ?

**Comment by gkleinfe** [comment] 2021-01-12 18:21
I'm still having the problem.  Here's what I'm doing.

1. We're hosting server on Nitrado
2. I'm shutting down the server.
3. I'm replacing the current liberation RX pbo (the one from 1/8/21) with today's build.
4. I'm starting the server back up.

When I start the server up, I'm using the commander role and logging in as admin.  When I do, none of the drop down list on the Admin panel are populated (see link to attached picture).  If I revert back to the 1/8/21 pbo, the lists are fine.

![Admin](https://user-images.githubusercontent.com/3876224/104355694-07c63a00-54d9-11eb-98d2-07380baa0623.png)

**Comment by tbox1911** [comment] 2021-01-13 10:23
Thanks for the details
I still can't reproduce :( 

I've tried (Hosted / Dedicated (Linux/Win)
Commander or not
language french/english
fresh start or backup
list still here !

but,
the date you tell me (1/8/21) match with commit "unban offline player #19"

the admin menu is client side. so, can you start your arma client with parameters " -showScriptErrors"
(reproduce the issue, login admin, open menu)

and send me the rpt file located in : C:\Users\<your username>\AppData\Local\Arma 3
example: arma3_x64_2021-01-13_10-42-41.rpt

that can help me to investigate

**Comment by Varrkan82** [comment] 2021-01-13 11:36
@tbox1911 will try in the evening. Working currently. But as I remember - this issue weren't appeared on my server when I was checking your improvements regarding a #19 issue. I was able to select any player in any field except an Unban field, it was empty. But a dropdown button works, menu was open whith no players in it (there wasn't banned player at that moment).

**Comment by gkleinfe** [comment] 2021-01-13 13:29
I ran the client as you instructed.  I included the log file as well as a screenshot of the error that now pops up with that setting.  This error pops up right after I click on Admin Menu.
![Error](https://user-images.githubusercontent.com/3876224/104458408-59be9c80-5579-11eb-8ba7-1fadfed7b5ce.png)
[Arma3_x64_2021-01-13_08-19-46.zip](https://github.com/tbox1911/Liberation-RX/files/5808827/Arma3_x64_2021-01-13_08-19-46.zip)

**Comment by tbox1911** [comment] 2021-01-13 13:35
thanks ! you found it

I take a look

**Comment by Varrkan82** [comment] 2021-01-13 20:28
@tbox1911 @gkleinfe not confirmed on my server with the last Altis PBO file
![image](https://user-images.githubusercontent.com/7004992/104506868-a1334000-55ee-11eb-8616-dc005da40db8.png)

**Comment by gkleinfe** [comment] 2021-01-13 21:02
I'm not familiar with how to execute the command you sent.  I am logged in as command and admin. When I press escape, I see the console, but really don't know how to use it.  Can you help?

**Comment by tbox1911** [comment] 2021-01-14 12:22
it's related to game save or save state.

as I say:  on a fresh server start, you should have an empty array [].

also,
"4. I'm starting the server back up."

Maybe you don't need this step (try without)
just start the server

to use console:
look at : https://community.bistudio.com/wikidata/images/8/88/Arma3_Debug_ExecutionResult.jpg

paste the code in "Execute", then click on "Local Exec". the result is copied in your clipboard

**Comment by gkleinfe** [comment] 2021-01-14 14:01
I did a fresh server start on a different server per my last post with the same result.  When I execute the command, nothing gets posted to the clipboard.

Would it be better if I give you access to my test server to check for yourself?  I'll give you the server and admin password.

**Comment by gkleinfe** [comment] 2021-01-14 21:19
I found something.  I removed all of my mods and the drop down lists were then available.  I started adding mods back to find the culprit. We use Community Based Addons mod (Steam link below) due to other mods requiring it that we use.  The CBA mod is causing the problem with the drop down lists.

https://steamcommunity.com/sharedfiles/filedetails/?id=450814997&searchtext=cba

**Comment by tbox1911** [comment] 2021-01-15 08:40
Hi,
you progress right !!
thanks a lot for your investigations.

now I can reproduce the issue, I'll work on it

**Comment by tbox1911** [comment] 2021-01-15 10:04
Should be fixed in the last build, please test

**Comment by gkleinfe** [comment] 2021-01-15 13:16
The latest build is showing drop down lists.  Thanks.

**Closed** 2021-01-18 14:03 UTC
